
[[_contribute]]
== Contributing to CometD

You can contribute to the CometD projects in several ways.
The CometD project values your contribution, of _any_ kind, and participating
in mailing lists, submitting bugs or documentation enhancements is equally
important as contributing code.

[[_contribute_mailing_lists]]
=== Contributing via Mailing Lists

The simplest way to contribute to the CometD project is to subscribe to the
CometD mailing lists. There are two mailing lists:

* *cometd-users@googlegroups.com*, to be used for discussions about how to use CometD.
  This is a low traffic mailing list.
  To subscribe to this list, go to the http://groups.google.com/group/cometd-users/[mailing list home page]
  and follow the instructions to apply for membership.
* *cometd-dev@googlegroups.com*, to be used for discussions about the CometD implementation.
  This is a low traffic mailing list.
  To subscribe to this list, go to the http://groups.google.com/group/cometd-dev/[mailing list home page]
  and follow the instructions to apply for membership.
  New members can join immediately the mailing list and receive messages,
  but their first post will be subject to moderation.

If you post for the first time, please allow some hour to moderators to review
the message and approve your post.
This is done to reduce spam to the minimum possible. 

[[_contribute_issue_reporting]]
=== Contributing by Reporting Issues

The CometD project maintains a http://bugs.cometd.org[JIRA issue tracker] that
is used to submit issues about the CometD project, from bugs to feature requests,
to documentation tasks, etc.
Virtually every activity is tracked in this JIRA instance. 

In order to submit an issue, you must have a valid Dojo Foundation login. 

If you do not have one already, you can create one by visiting
http://my.dojofoundation.org/register[this link].
Choose your username and password, follow the instructions, and once your account
is created, do not try to login to the Dojo foundation, as you do not need to.
Go back to JIRA and login to JIRA with the account you just created. 

Once you are logged in into JIRA, you will be able to submit new issues and browse
and comment existing ones.
JIRA is a very nice issue tracking tool, and you can customize to your needs.
For more information about JIRA, see the http://www.atlassian.com/software/jira[JIRA documentation]. 

[[_contribute_code]]
=== Contributing Code Fixes and Enhancements

The CometD project code is hosted at https://github.com/cometd[GitHub CometD Organization].
The repository for the CometD libraries is https://github.com/cometd/cometd.
You can build the CometD project yourself by following the instruction in
<<_build,the build section>>.

In order to contribute code, you need to have a Contributor License Agreement
(CLA) with the Dojo Foundation.

Don't worry ! It's easy and you can fill it online.
Since contributing code normally requires also interaction with JIRA, it is
best if you already have a Dojo Foundation account before filling the CLA.
see also <<_contribute_issue_reporting,here>> for how to create a Dojo Foundation account.

Go to the http://dojofoundation.org/about/claForm[Dojo Foundation CLA online form],
read it carefully and fill in the form at the bottom of the page.
Once you have the CLA in place, you can contribute code via
https://help.github.com/articles/using-pull-requests[GitHub pull requests].

[[_contribute_documentation]]
=== Contributing to Documentation & Tutorials

The repository for the CometD documentation is https://github.com/cometd/cometd-documentation,
while the repository for the CometD tutorials is https://github.com/cometd/cometd-tutorials.
The CometD documentation and tutorials are written in http://asciidoc.org/[AsciiDoc],
and built using Maven and the http://asciidoctor.org[AsciiDoctor] Maven Plugin.

There is no need for a Contributor License Agreement to contribute fixes or
enhancements to the documentation or the tutorials, you can just contribute
via https://help.github.com/articles/using-pull-requests[GitHub pull requests].
