
[[_extensions_reload]]
=== Reload Extension

The reload extension allows CometD to load or reload a page without having
to re-handshake in the new (or reloaded) page, thereby resuming the existing
CometD connection.
This extension requires only the client-side extension. 

==== Enabling the Client-side Extension

The `dojox/cometd/reload.js` provides the client side extension binding for
Dojo, and it is sufficient to use Dojo's `dojo.require` mechanism:

====
[source,javascript]
----
require(["dojox/cometd", "dojox/cometd/reload"], function(cometd)
{
    ...
});
----
====

The example above is valid also when using the `require()` syntax with jQuery.

The file `jquery.cometd-reload.js` provides the client-side extension
binding for jQuery.
When you are not using the `require()` syntax, you must include the
the http://plugins.jquery.com/project/Cookie[jQuery cookie plugin],
the implementation file and the jQuery extension binding
in the HTML page via the `<script>` tag:

====
[source,javascript]
----
<script type="text/javascript" src="jquery.cookie.js"></script>
<script type="text/javascript" src="ReloadExtension.js"></script>
<script type="text/javascript" src="jquery.cometd-reload.js"></script>
----
====

In both Dojo and jQuery extension bindings, the extension is registered
on the default `cometd` object under the name "reload".

==== Configuring the Reload Extension

The reload extension accepts the following configuration parameters: 

[cols="1,1,10", options="header"]
|===
| Parameter Name
| Default Value
| Parameter Description

| cookieName
| org.cometd.reload
| The name of the short-lived cookie the reload extension uses to save the connection state details

| cookiePath
| /
| The path of the short-lived cookie the reload extension uses

| cookieMaxAge
| 5
| The max age, in seconds, of the short-lived cookie the reload extension uses
|===

The JavaScript `cometd` object is normally already configured with the
default reload extension configuration.
To reconfigure the reload extension: 

* Reconfigure the extension at startup: 
+
====
[source,javascript]
----
var cometd = dojox.cometd; // Use $.cometd if using jquery
cometd.getExtension('reload').configure({
    cookieMaxAge: 15
});
----
====
* Reconfigure the extension every time the `cometd.reload()` method is invoked:
+
====
[source,javascript]
----
var cometd = dojox.cometd; // Use $.cometd if using jquery
...
cometd.reload({
    cookieMaxAge: 15
});
----
====

If you increase the `maxCookieAge`, be aware that you should probably increase
the value of `maxInterval` too (see also
<<_java_server_configuration,the server configuration section>>), to avoid the
server expiring the session while the page is reloading.

==== Understanding Reload Extension Details

The reload extension is useful to allow users to reload CometD pages, or to
navigate to other CometD pages, without going through a disconnect and handshake
cycle, thus resuming an existing CometD session on the reloaded or on the new page.

When reloading or navigating away from a page, browsers will destroy the
JavaScript context associated to that page, and interrupt the connection
to the server too.
On the reloaded or on the new page, the JavaScript context is recreated
anew by the browser, but the CometD JavaScript library has lost all the
CometD session details that were established in the previous page.
In absence of the reload extension, application need to go through another
handshake step to recreate the CometD session details needed.

The reload extension gives the ability to resume the CometD session in the
new page, by re-establishing the previously successful CometD session.
This is useful especially when the server builds a stateful context for the
CometD session that is not to be lost just because the user refreshed the page,
or navigated to another part of the same CometD web application.
A typical example of this stateful context is when the server needs to
guarantee message delivery (see also
<<_extensions_acknowledge,the acknowledge extension section>>). In this case,
the server has a list of messages that have not been acknowledged by the client,
and if the client reloads the page, without the reload extension this list of
messages will be lost, causing the client to potentially loose important messages.
With the reload extension, instead, the CometD session is resumed and it will
appear to the server as if it was never interrupted, thus allowing the server
to deliver to the client the unacknowledged messages.

The reload extension works in this way: on page load, the application configures
the CometD object, registers channel listeners and finally calls `cometd.handshake()`.
This handshake normally contacts the server and establishes a new CometD session,
and the reload extension tracks this successful handshake.
On page reload, or when the page is navigated to another CometD page, the
application code must call `cometd.reload()` (for example, on the page
unload event handler). When `cometd.reload()` is called, the reload extension
saves a short-lived cookie with the CometD session state details.
When the new page loads up, it will execute the same code executed on the first
page load, namely the code that configured CometD, that registered channel
listeners, and that finally called `cometd.handshake()`.
The reload extension is invoked upon the new handshake, sees that the short
lived cookie saved previously is there, and re-establishes the CometD session
with the information stored in the short lived cookie.

A simple example follows: 

====
[source,html]
----
<html>
    <head>
        <script type="text/javascript" src="dojo/dojo.js"></script>
        <script type="text/javascript">
            dojo.require("dojox.cometd");
            dojo.require("dojox.cometd.reload");

            dojox.cometd.configure({ url: "http://localhost:8080/context/cometd", logLevel: "info" });

            // Always subscribe to channels from successful handshake listeners
            dojox.cometd.addListener("/meta/handshake", new function(m)
            {
                if (m.successful)
                {
                    dojox.cometd.subscribe("/some/channel", function() { ... });
                    dojox.cometd.subscribe("/some/other/channel", function() { ... });
                }
            });

            // On page unload, call dojox.cometd.reload()
            dojo.addOnUnload(dojox.cometd, "reload");

            // Finally, handshake
            dojox.cometd.handshake();
        </script>
    </head>
    <body>
    ...
    </body>
</html>
----
====
