
[[_java_server_transports]]
==== Server Transports

TODO: review this chapter in light of JSR 356.

<<_bayeux,The Bayeux protocol>> defines two mandatory transports:
+long-polling+ and +callback-polling+.
These two transports are automatically configured in the +BayeuxServer+
instance, and there is no need to explicitly specify them in the configuration.

For the +websocket+ transport things are different because there is no
standard API for server-side WebSocket yet (it is under consideration for
the Servlet 3.1 specification), and therefore any implementation binds you
to the servlet container implementation.

[IMPORTANT]
====
The CometD project borrows many libraries from the http://eclipse.org/jetty[Jetty]
project.
While CometD itself is not bound to Jetty, and you can plug in other WebSocket
implementations , the CometD projects ships a +websocket+ server transport based on Jetty's WebSocket.
As such, if you want to use the CometD WebSocket server transport shipped by
default, you _must_ run your web application in Jetty.
====

[NOTE]
====
While for the +websocket+ _server_ transport you are bound to run your web
application in a specific servlet container, it is possible to use the +websocket+
_client_ transport on the server (for example to communicate with another WebSocket
CometD server) in any servlet container.

While Jetty's WebSocket server library works only in Jetty, Jetty's WebSocket
client library is portable and does not bind you to any servlet container.
For example, it is possible to have a client communicating via HTTP to a CometD
web application running in Tomcat, which communicates via WebSocket to another
CometD web application running in Jetty.
====

To configure the +websocket+ transport on the server, follow these instructions:

. Change the +CometdServlet+ configuration in +web.xml+ (see also
  <<_java_server_configuration,the server configuration section>>) to specify the
  +transports+ parameter, as follows:
+
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
         version="2.5">

    <servlet>
        <servlet-name>cometd</servlet-name>
        <servlet-class>org.cometd.server.CometdServlet</servlet-class>
        <init-param>
            <param-name>transports</param-name>
            <param-value>org.cometd.websocket.server.WebSocketTransport</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>cometd</servlet-name>
        <url-pattern>/cometd/*</url-pattern>
    </servlet-mapping>

</web-app>
----
====
+
You do not need to worry about the +long-polling+ and +callback-polling+ transports.
Those are present in any case, as the +transports+ parameter specifies _additional_,
 non-required transports.

. Be sure that you include the dependency +org.cometd.java:cometd-websocket-jetty+.
  This is very easy to do if you're using Maven: just declare the additional dependency
  in your application's +pom.xml+ file.
  If you are not using Maven, you need to make sure that +cometd-websocket-jetty-<version>.jar+
  is present in the +WEB-INF/lib+ directory of your web application .war file.
. If you plan to use the +websocket+ _client_ transport in your web application,
  and you are not using Maven, make sure that +jetty-websocket-<version>.jar+,
  +jetty-io-<version>.jar+ and +jetty-http-<version>.jar+ are also present in the
  +WEB-INF/lib+ directory of your web application .war file.

If you have configured your web application to support cross-domain HTTP calls
(see also <<_java_server_configuration_advanced,this section>>), you do not
need to worry because the +CrossOriginFilter+ is by default disabled for the
WebSocket protocol.
