
:numbered!:

[preface]
== Preface

http://cometd.org/[CometD] is a scalable web event routing bus that allows you
to write low-latency, server-side, event-driven web applications.
Typical examples of such applications are stock trading applications, web chat
applications, online games, and monitoring consoles.

CometD makes use of an http://en.wikipedia.org/wiki/AJAX[Ajax] push technology
pattern known as http://en.wikipedia.org/wiki/Comet_(programming)[Comet], but
also uses emerging web standards such as
http://en.wikipedia.org/wiki/WebSocket[WebSocket] for low latency communication.

The CometD project provides Java and JavaScript libraries that allow you to
write low-latency, server-side, event-driven web applications in a simple and
portable way.
You can therefore concentrate on the business side of your application rather
than worrying about low-level details such as the transport (HTTP or WebSocket),
the scalability and the robustness.
The CometD libraries provide these latter characteristics. 

If you are new to CometD, you can follow this learning path: 

. Read <<_installation,the installation section>> to download, install CometD and to try out its demos.
. Read <<_primer,the primer section>> to get your hands dirty with CometD with a step-by-step tutorial.
. Read <<_concepts,the concepts section>> to understand the abstractions that CometD defines.
. Study the CometD demos that ship with the CometD distribution . 
. Read the rest of this reference book for further details.

You can contribute to the CometD project and be involved in the CometD community,
including:

* Trying it out and reporting issues at http://bugs.cometd.org
* Participating in the http://groups.google.com/group/cometd-users/[CometD Users]
and http://groups.google.com/group/cometd-dev/[CometD Development] mailing lists.
* Helping out with the documentation by contacting the mailing lists or by reporting issues.
* Spreading the word about CometD in your organization.

:numbered:
